spring:
  datasource:
    url: jdbc:postgres://localhost:5433/ems
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true